apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.applicationSet.name }}
spec:
  generators:
    - list:
        elements:
          - cluster: {{ .Values.env }}
            url: https://kubernetes.default.svc
            env: {{ .Values.env }}

      selector:
        matchLabels:
          env: {{ .Values.env }}
  template:
    metadata:
      name: '{{.Values.applicationSet.name}}-applicationset'
    spec:
      project: {{ .Values.project }}
      source:
        repoURL: {{ .Values.applicationSet.source.repoURL }}
        targetRevision: {{ .Values.applicationSet.source.targetRevision }}
        path: {{ .Values.applicationSet.source.path }}
        helm:
          valueFiles: {{ .Values.applicationSet.source.helm.valueFiles }}

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: {{.Values.applicationSet.namespace}}
