apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project }}
  namespace: argocd
spec:
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  # Project description
  description: App project
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: '*'
      server: '*'
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'
